#!/usr/local/perl/
#Take output from Fierce DNS scanner and input into CSV file

my $input_file_name = $ARGV[0];
#print $input_file_name;
open my $file_lines, '<', $input_file_name;
chomp(my @lines = <$file_lines>);
close $file_lines;
#print @lines;

foreach (@lines)
{
        if ($_ == m/^([0-9]{1,3}\.){3}[0-9]{1,3}$/)
          {print "no \n";}
        else
          {print $_ . "\n";}
}